In [1]:
import numpy as np
a1=np.ones((3,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2]:
a1=np.ones((3,3),dtype=np.int16)
a1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [3]:
str_arr=np.array(['nik','kum','hil'])
str_arr

array(['nik', 'kum', 'hil'], dtype='<U3')

In [4]:
str_arr[1]='kumar'

In [5]:
str_arr


array(['nik', 'kum', 'hil'], dtype='<U3')

In [6]:
str_arr[1]='k'

In [7]:
str_arr


array(['nik', 'k', 'hil'], dtype='<U3')

In [8]:
vec1=np.array([1,-1,0])
vec2=vec1/0
vec2

C:\Users\nikhil\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
C:\Users\nikhil\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([ inf, -inf,  nan])

In [9]:
for i in vec2:
    print(i)
    print('----------')
    print(str(i==np.inf))
    print(str(i==-np.inf))
    print(str(i==np.nan))#does not work

inf
----------
True
False
False
-inf
----------
False
True
False
nan
----------
False
False
False


In [11]:
for i in vec2:
    print(i)
    print('----------')
    print(str(i==np.inf))
    print(str(i==-np.inf))
    print(str(np.isnan(i)))#does work

inf
----------
True
False
False
-inf
----------
False
True
False
nan
----------
False
False
True


In [12]:
for i in vec2:
    print(i)
    print('----------')
    print(str(np.isfinite(i)))
    print(str(np.isinf(i)))
    print(str(np.isnan(i)))#does work

inf
----------
False
True
False
-inf
----------
False
True
False
nan
----------
False
False
True


In [13]:
vec4=np.ones(5)
vec4[0]=np.nan
vec4

array([nan,  1.,  1.,  1.,  1.])

In [14]:
np.sum(vec4)

nan

In [16]:
np.nansum(vec4)

4.0

In [18]:
vec1=np.ones(5)
vec1

array([1., 1., 1., 1., 1.])

In [19]:
vec1.dtype

dtype('float64')

In [24]:
vec1.dtype=np.int16
vec1

array([    0,     0,     0, 16368,     0,     0,     0, 16368,     0,
           0,     0, 16368,     0,     0,     0, 16368,     0,     0,
           0, 16368], dtype=int16)

In [25]:
vec1=np.ones(5)
vec1=np.array(vec1,dtype=np.int8)
print(vec1)

[1 1 1 1 1]


In [28]:
vec1.dtype

dtype('int8')

In [31]:
zro=np.zeros((2,2,2))
zro

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [32]:
ran_arr=np.random.rand(3,3)
ran_arr

array([[0.34652048, 0.30047269, 0.84074164],
       [0.0839923 , 0.48381435, 0.28696627],
       [0.76905195, 0.87412584, 0.54109827]])

In [33]:
tupl=np.array([[(1,2,3),(4,5,6)],[(1,2,3),(4,5,6)]])
tupl

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [36]:
np.array([[(1,2.3,3),(4,np.nan,6)],[(1,'str',3),(4,5,6)]])

array([[['1', '2.3', '3'],
        ['4', 'nan', '6']],

       [['1', 'str', '3'],
        ['4', '5', '6']]], dtype='<U32')

In [37]:
cop=tupl
cop

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [38]:
cop[0][0]=10

In [39]:
cop

array([[[10, 10, 10],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [40]:
tupl

array([[[10, 10, 10],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [41]:
cop1=tupl.copy()

In [42]:
cop1

array([[[10, 10, 10],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [43]:
cop1[0][0]=100

In [44]:
cop1

array([[[100, 100, 100],
        [  4,   5,   6]],

       [[  1,   2,   3],
        [  4,   5,   6]]])

In [50]:
tupl=np.arange(10)

In [51]:
%pwd

'C:\\Users\\nikhil\\Desktop\\python'

In [52]:
np.save("tupl",tupl)

In [53]:
np.savetxt("c.csv",tupl,delimiter=";")

In [54]:
file=open("c.csv","r")
for n in file:
    print(n)
file.close()

0.000000000000000000e+00

1.000000000000000000e+00

2.000000000000000000e+00

3.000000000000000000e+00

4.000000000000000000e+00

5.000000000000000000e+00

6.000000000000000000e+00

7.000000000000000000e+00

8.000000000000000000e+00

9.000000000000000000e+00



In [56]:
tupl

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
file=np.load("tupl.npy")
file

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
file=np.loadtxt("c.csv",delimiter=";")
file

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])