In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [3]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
list2d=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(list2d)

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
list2d=[[1,2,[1,2,3]],[4,5,[4,5,6]],[7,8,[7,8,9]]]
arr=np.array(list2d)

In [8]:
print(arr)

[[1 2 list([1, 2, 3])]
 [4 5 list([4, 5, 6])]
 [7 8 list([7, 8, 9])]]


In [9]:
list2d=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(list2d)

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr[0]

array([1, 2, 3])

In [12]:
arr[0][0]

1

In [13]:
arr[2][2]

9

In [14]:
arr[][2]

SyntaxError: invalid syntax (<ipython-input-14-997a859122b7>, line 1)

In [15]:
arr[1][4]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [16]:
arr[:][:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
zer=np.zeros(5,5)

TypeError: data type not understood

In [20]:
zer=np.zeros((5,5))

In [21]:
zer

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
ran=np.arange(0,10)
ran

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ran=np.arange(0,20,2)
ran

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])